### ISSUE TITLE
HTTPS with Let's Encrypt certificate

### ISSUE THREAD

**Issue by iBobik** [chilts/nginx-generator#2]
Would be nice if it can configure HTTPS and automatically fetch certificate by [letsencrypt](https://github.com/letsencrypt/letsencrypt) utility.

**Comment by chilts** [comment]
Yep, that sounds good. I'd like to do it too, though I don't yet have account access on LetsEncrypt at the moment.

@iBobik Are you using this package at the moment?

**Comment by iBobik** [comment]
No, I also wait for public access :-)

But as a developer of „some server-related tool” you have chance to get
access.

Jan Pobořil

2015-10-26 21:51 GMT-05:00 Andrew Chilton notifications@github.com:

**Comment by iBobik** [comment]
It is now in public beta.

Example use-case:

If I call generator with e.g. `--https` it will check if there is also `--https-cert` and `--https-key` with files and if not it will run Let's Encypt utility. Then it will create configuration with provided certificate (whenever it is from Let's Encrypt or from file). Alternative is to let Let`s Encrypt utility to configure NginX, but I am not sure if it don't collide with something from this genarator.

There also can be `--no-https-redirect` option. It is good to add 301 redirect from HTTP to HTTPS by default.

Also it is good to call utility with `--renew-by-default` parameter, so automatic renewal will work (if `letsencrypt-renewer` will be added to crontab).

**Comment by mikaoelitiana** [comment]
This would be a great feature!!

**Comment by chilts** [comment]
I think there are better ways of doing LetsEncrypt now. Also, I'm not using this package anymore, but if anyone is still using it and wants to do this, or even wants git commit access, I'm happy to add it. Other than that, I'll close since this has been open so long and we'll see if anyone still wants it.
